acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('pdfread/', include("pdfread.urls")),
    path('vote/', include("vote.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>',views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel, name="cancel"),
    path('create/', views.create, name="create")
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=200)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 20:
            return f"{self.content[:20]}  ..."
        return self.content

    

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    chname = models.CharField(max_length=200)
    chpic = models.ImageField(upload_to="vote/%y")
    chcom = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.topic}-{self.chname}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
from django.utils import timezone

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        cn = request.POST.getlist("cname")
        cp = request.FILES.getlist("cpic")
        cc = request.POST.getlist("ccom")
       
        if len(cn) > 1:
            t = Topic(subject=s, content=c, maker=request.user, pubdate=timezone.now())
            t.save()
            for name, pic, com in zip(cn, cp, cc):
                Choice(topic=t, chname=name, chpic=pic, chcom=com).save()
            return redirect("vote:index")
    return render(request, "vote/create.html")


def cancel(request, tpk):
    t = Topic.objects.get(id=tpk)
    t.voter.remove(request.user) # 투표안한사람으로 만듬
    # 나를 참조하고 있는 보기들중에 유저있으면 빼네는거~!!
    # cset = t.choice_set.all()
    # for i in cset:
    #     if request.user in i.choicer.all():
    #         i.choicer.remove(request.user)
    #         break
    # 유저 입장에서 내가 고른 보기들 중 topic 이 t 인 친구를 고르는것!!!
    request.user.choice_set.get(topic=t).choicer.remove(request.user)
    
    return redirect("vote:detail", tpk)

def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("ch")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect('vote:detail', tpk)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t":t,
        "cset":c
    }
    return render(request, "vote/detail.html", context)

# Create your views here.
def index(request):
    t = Topic.objects.all()
    t = t.order_by('-pubdate')
    context = {
        "tset" : t
    }
    return render(request, "vote/index.html", context)

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}

    <div class="container mt-5 mb-5">
        <h1><b>토픽생성</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="sub" class="form-control mt-5" placeholder="투표 주제를 넣어주세요.">
            <textarea class="form-control mt-4" name="con" style="height: 150px;" placeholder="투표에 대해 간단하게 설명해주세요."></textarea>

            <div class="text-center mt-4">
                <button type="button" onclick="make()" class="btn btn-dark">보기생성</button>
                <button class="btn btn-primary">생성하기</button>
            </div>
            <div id="here" class="row"></div>   
        </form> 
    </div>
    
    
    
    <script>
        function make(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute('class', 'col-lg-6 mt-5');
            n.innerHTML = '<div class="card" style="padding: 20px;">\
                    <input type="text" name="cname" class="form-control" placeholder="보기이름을 입력하세요.">\
                    <input type="file" name="cpic" class="form-control">\
                    <textarea class="form-control" name="ccom" placeholder="보기에 대해 간단하게 설명해주세요."></textarea>\
                </div>';
            d.appendChild(n);
        }
    </script>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
{% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>{{ t.subject }}</b></h1>

        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control" style="height: 250px;" disabled>{{ t.content }}</textarea>
            </div>
            <div class="col-lg-4" style="margin: auto;">
                <img src="{{ t.maker.getpic }}" width="100%">
                <div class="text-center mt-4">
                    <h4>made by <b>{{ t.maker }}</b></h4>
                </div>
            </div>
        </div>

        {% if user in t.voter.all %}
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col-lg-4">
                        <img src="{{ i.chpic.url }}" width="100%">
                        <div class="text-center mt-3">
                            <h5><b>{{ i.chname }}</b></h5>
                        </div>
                        <div class="progress mt-4 mb-4">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ i.choicer.all.count | div:t.voter.all.count | mul:100 }}%">{{ i.choicer.all.count | div:t.voter.all.count | mul:100 }} %</div>
                        </div>
                        <textarea class="form-control" style="height: 80px;" disabled>{{ i.chcom }}</textarea>
                    </div>
                {% endfor %}
            </div>
            <div class="text-end mt-4">
                <a href="{% url 'vote:cancel' t.id %}" class="btn btn-secondary">투표취소</a>
            </div>
        {% else %}
            <form method="post" action="{% url 'vote:vote' t.id %}">
                {% csrf_token %}
                <div class="row mt-5">
                    {% for i in cset %}
                        <div class="col-lg-4">
                            <div class="text-center mb-3">
                                <input class="form-check-input" type="radio" name="ch" value="{{i.id}}" {% if forloop.first %} checked {% endif %}>
                            </div>
                            <img src="{{ i.chpic.url }}" width="100%">
                            <div class="text-center mt-3">
                                <h5><b>{{ i.chname }}</b></h5>
                            </div>
                            <textarea class="form-control" style="height: 80px;" disabled>{{ i.chcom }}</textarea>
                        </div>
                    {% endfor %}
                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-dark">투표하기</button>
                </div>
            </form>
        {% endif %}


    </div>

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">

        <h1><b>투표함</b></h1>

        <div class="text-end">
            <a href="{% url 'vote:create' %}" class="btn btn-dark btn-lg">TOPIC생성</a>
        </div>

        <div class="row">
            {% for i in tset %}
                <div class="col-lg-4 mt-3">
                    <div class="card" style="width: 100%;">
                        <img src="{{ i.maker.getpic }}" class="card-img-top" width="100%">
                        <div class="card-body" {% if user in i.voter.all %} style="background-color: rgba(166, 255, 0, 0.219);" {% endif %}>
                            <h4 class="card-title"><b>{{ i.subject }}</b></h4>
                            <p class="card-text">{{ i.summary }}</p>
                            <div class="text-center">
                                <a href="{% url 'vote:detail' i.id %}" class="btn btn-dark btn-lg">{% if user in i.voter.all %}결과보기{% else %}투표하기{% endif %}</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>


    </div>
{% endblock %}