acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('trans/', include("trans.urls")),
    path('pdfread/', include("pdfread.urls")),
    path('vote/', include("vote.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User


# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject
    
    def summary(self):
        if len(self.content) > 100:
            return f"{self.content[:100]}   ..."
        return self.content

class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.b}_{self.replyer}"

board/views.py
from email import message
from django.shortcuts import render, redirect
from .models import Board, Reply
# Create your views here.
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages



def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    action = request.GET.get("action", "")
    if action == 'add':
        b.likey.add(request.user)
    else:
        b.likey.remove(request.user)
    return redirect("board:detail", bpk)

    

def index(request):
    pg = request.GET.get("page", 1)
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            messages.error(request, "혼나!")
            b = Board.objects.all()
    else:
        b = Board.objects.all()

    b = b.order_by('-pubdate')

    pag = Paginator(b,5)
    obj = pag.get_page(pg)

    context = {
        "bset": obj,
        "cate": cate,
        "kw": kw
    }
    return render(request, "board/index.html", context)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        r.delete()
    else:
        messages.error(request, "혼나!")
    return redirect("board:detail", bpk)

def creply(request, bpk):
    c = request.POST.get("com")
    b = Board.objects.get(id=bpk)
    Reply(b=b, replyer=request.user, comment=c, pubdate=timezone.now()).save()
    return redirect("board:detail", bpk)

def update(request, bpk):
    b = Board.objects.get(id=bpk)
    # 자신의 글이 아니면 board 의 index 로 이동!!!
    if b.writer != request.user:
        messages.error(request, "혼나!")
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:detail", bpk)
    context = {
        "b":b
    }
    return render(request, "board/update.html", context)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        if s and c:
            Board(subject=s, content=c, writer=request.user, pubdate=timezone.now()).save()
            return redirect("board:index")

    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        messages.error(request, "혼나!")
    return redirect("board:index")

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b": b,
        "rset" : r
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시글 작성</b></h1>
        
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="sub" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 100px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>{{ b.subject }}</b></h1>

        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control" disabled style="height: 300px;">{{ b.content }}</textarea>
            </div>
            <div class="col-lg-4 text-center" style="margin: auto;">
                <img src="{{ b.writer.getpic }}" height="180px">
                <div class="mt-3" style="font-size:24px">
                    written by <b>{{ b.writer }}</b>
                </div>
                <div class="text-end mt-3">
                    {{ b.pubdate | date:'Y년 n월 j일 G:i'}}
                </div>
            </div>
        </div>

        <div class="text-end mt-4">
            <a href="{% url 'board:index' %}" class="btn btn-dark">BACK</a>
            {% if user == b.writer %}
                <a href="{% url 'board:update' b.id %}" class="btn btn-secondary">MOD</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    DEL
                </button>
            {% endif %}
        </div>
        
        <div class="text-end mt-3">
            {% if user in b.likey.all %}
                <a href="{% url 'board:likey' b.id %}?action=remove" class="btn btn-danger">👎</a>
            {% else %}
                <a href="{% url 'board:likey' b.id %}?action=add" class="btn btn-primary">👍</a>
            {% endif %}
        </div>

    </div>
    
    

    <hr>
    <div class="container" style="width: 60%;">
        
        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class="row text-end">
                <div class="col-lg-10">
                    <input type="text" name="com" class="form-control" placeholder="댓글을 작성해주세요">
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-dark">댓글생성</button>
                </div>
            </div>
        </form>

        {% if rset %}
            {% for i in rset %}
                <div class="row mt-5">
                    <div class="col-lg-3">
                        <img src="{{ i.replyer.getpic }}" width="100%">
                        <div class="mt-3 text-center" style="font-size: larger;">
                            <b>{{i.replyer}}</b>
                        </div>
                    </div>
                    <div class="col-lg-9" style="margin: auto;">
                        <textarea class="form-control" disabled style="height: 100px;">{{ i.comment }} </textarea>
                        <div class="text-end mt-2">
                            {{ i.pubdate | date:'Y년 n월 j일 G:i'}}
                        </div>
                        <div class="text-end mt-2">
                            {% if user == i.replyer %}
                                <a href="{% url 'board:dreply' b.id i.id %}"><button class="btn btn-danger">댓글삭제</button></a>
                            {% endif %}    
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        
        {% endif %}

    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">게시글 삭제 알림</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}" class="btn btn-danger">삭제</a>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/board/index.html
{% extends 'base.html' %}

{% block con %}

{% load mathfilters %}

    <div class="container mt-5 mb-5">
        <h1><b>게시판</b></h1>

        <div class="text-end">
            <a href="{% url 'board:create' %}" class="btn btn-dark">CREATE</a>
        </div>


        <!-- 테이블 -->
        <table class="table mt-3">
            <thead style="background-color: black; color:white; font-size: 20px;">
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                    <th scope="col">LIKEY</th>
                </tr>
            </thead>
            <tbody>
                {% if bset %}
                    {% for i in bset %}
                        <tr>
                            <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                            <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                            <td>{{ i.summary }}</td>
                            <td>{{ i.writer }}</td>
                            <td>{{ i.likey.all.count }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                        <tr class="text-center">
                            <th colspan="5">검색결과가 없습니다 😂</th>
                        </tr>
                    {% else %}
                        <tr class="text-center">
                            <th colspan="5">첫 게시글을 작성해주세요 🤣</th>
                        </tr>
                    {% endif %}
                {% endif %}
                
            </tbody>
        </table>


        <!-- 페이징 -->
        <nav aria-label="Page navigation example" class="mt-5">
            <ul class="pagination justify-content-center pagination-sm">
                {% if bset.has_previous %}
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}">이전</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link">처음</a></li>
                    <li class="page-item disabled"><a class="page-link">이전</a></li>
                {% endif %}

                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                        <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                    {% endif %}
                {% endfor %}
        
                {% if bset.has_next %}
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}">다음</a></li>
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">마지막</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link">다음</a></li>
                    <li class="page-item disabled"><a class="page-link">마지막</a></li>
                {% endif %}
            </ul>
        </nav>


        <form>
            <div class="row mt-5 mb-5">
                <div class="col-lg-2">
                    <select name="cate" class="form-select" aria-label="Default select example">
                        <option value="sub" {% if cate == 'sub' %} selected {% endif %}>제목</option>
                        <option value="wri" {% if cate == 'wri' %} selected {% endif %}>글쓴이</option>
                        <option value="con" {% if cate == 'con' %} selected {% endif %}>내용</option>
                    </select>
                </div>
                <div class="col-lg-9">
                    <input type="text" class="form-control" name="kw" value="{{kw}}">
                </div>
                <div class="col-lg-1">
                    <button class="btn btn-dark">검색</button>
                </div>
            </div>
        </form>




    </div>
    

    <style>
        a.sub {
            text-decoration: none;
            font-size: 18px;
            color:black;
            font-weight: bold;
        }
        a.sub:hover{
            color:red;
        }
    </style>


{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <form method="post">
            {% csrf_token %}
            <h1><b>게시글수정</b></h1>
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="sub" value="{{ b.subject }}"class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" disabled value="{{ b.writer }}">
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 100px;">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정하기</button>
            </div> 
        </form>
    </div>
{% endblock %}